services:
  # Citation Needed backend application
  citation-needed:
    build: .
    ports:
      - "8000:8000"
    environment:
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - FIRECRAWL_API_KEY=${FIRECRAWL_API_KEY:-}
      - SEARXNG_URL=http://searxng:8080
    depends_on:
      - searxng
    volumes:
      - ./usage_data.json:/app/usage_data.json
    restart: unless-stopped
    networks:
      - citation-needed-network

  # SearXNG search engine
  searxng:
    image: searxng/searxng:latest
    ports:
      - "8080:8080"
    volumes:
      - ./searxng/settings.yml:/etc/searxng/settings.yml:ro
    environment:
      - SEARXNG_SECRET_KEY=Z58Mlo3fyRSfl1ym8E1b7rgoMDEYGSQA
    restart: unless-stopped
    networks:
      - citation-needed-network

  # Frontend development server
  frontend:
    image: node:22-alpine
    working_dir: /app
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
    command: sh -c "npm install && npm run dev -- --host 0.0.0.0"
    environment:
      - NODE_ENV=development
    restart: unless-stopped
    networks:
      - citation-needed-network

networks:
  citation-needed-network:
    driver: bridge

volumes:
  searxng-data: