[tool.ruff]
# Python version
target-version = "py312"

# Line length
line-length = 100

# Exclude directories
exclude = [
    ".git",
    "__pycache__",
    ".venv",
    "venv",
    "build",
    "dist",
    "*.egg-info",
]

[tool.ruff.lint]
# Enable specific rule sets
select = [
    "E",    # pycodestyle errors
    "W",    # pycodestyle warnings
    "F",    # Pyflakes
    "I",    # isort
    "B",    # flake8-bugbear
    "C4",   # flake8-comprehensions
    "UP",   # pyupgrade
    "SIM",  # flake8-simplify
]

# Ignore specific rules
ignore = [
    "E501",   # Line too long (handled by formatter)
    "B008",   # Do not perform function calls in argument defaults
    "C901",   # Function is too complex
    "W191",   # Indentation contains tabs
]

[tool.ruff.lint.isort]
# Known first party modules
known-first-party = ["models", "search", "ui"]

# Import order
force-single-line = false
lines-after-imports = 2

[tool.ruff.lint.per-file-ignores]
# Allow unused imports in __init__.py files
"__init__.py" = ["F401"]

# Allow print statements in app.py (main file)
"app.py" = ["T201"]

[tool.ruff.lint.pycodestyle]
max-doc-length = 100

[tool.ruff.format]
# Use double quotes for strings
quote-style = "double"

# Use spaces for indentation
indent-style = "space"

# Respect existing line endings
skip-magic-trailing-comma = false

# Docstring formatting
docstring-code-format = false