general:
  debug: false
  instance_name: "SearXNG"

search:
  safe_search: 0
  autocomplete: ""
  formats:
    - html
    - json

server:
  port: 8080
  secret_key: "Z58Mlo3fyRSfl1ym8E1b7rgoMDEYGSQA"
  method: "GET"
  limiter: false
  public_instance: false
  public: false        # more permissive for local
  bind_address: 0.0.0.0
  port: 8080
  cors: "*"
  http_methods:
    - GET
    - POST

ui:
  default_theme: simple

engines:
  - name: wikipedia
    engine: wikipedia
    shortcut: wp

  - name: duckduckgo
    engine: duckduckgo
    shortcut: ddg

  - name: google
    engine: google
    shortcut: go

doi_resolvers:
  doi.org: 'https://doi.org/'

default_doi_resolver: 'doi.org'